input {
  http {
    id => "cybersentinel_json_http"
    host => "0.0.0.0"
    port => 8080
    codec => json
  }
  beats {
    id => "cybersentinel_beats"
    port => 5044
  }
}

filter {
  if [timestamp] {
    date {
      match => ["timestamp", "ISO8601", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
      target => "@timestamp"
    }
  }
  mutate {
    add_field => { "[@metadata][normalized]" => "true" }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST:http://elasticsearch:9200}"]
    index => "cybersentinel-events-%{+YYYY.MM.dd}"
    ssl_enabled => false
  }
  stdout { codec => json_lines }
}
